version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          BUNDLER_VERSION: 2.2.32
          RAILS_ENV: test
          DB_HOST: '127.0.0.1'
          DB_USERNAME: 'root'
          DB_PASSWORD: 'password'

      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/api/Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle config sert path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/repo/api
      
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "~/repo/api/Gemfile.lock" }}

      - run:
          command: bundle exec rails db:create
          working_directory: ~/repo/api

      - run:
          command: bundle exec rake db:schema:load
          working_directory: ~/repo/api

      - run:
          name: Rubocop
          command: bundle exec rubocop
          working_directory: ~/repo/api

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      # correct reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
